language: node_js
node_js:
  - "lts/*"
before_script:
  - npm install -g pkg
script:
  - 'if [ "$TRAVIS_OS_NAME" != "windows" ]; then npm run lint; fi'
  - npm test
  - npm run coverage
  - npm run build
jobs:
  include:
    # Define the release stage that runs semantic-release
    - stage: Create Release
      deploy:
        provider: script
        skip_cleanup: true
        script: npx semantic-release
    - stage: Build and Deploy
      os: linux
      deploy:
        provider: releases
        api_key: "$GH_TOKEN"
        skip_cleanup: true
        file: "$TRAVIS_OS_NAME.zip"
      before_deploy:
        - pkg -o "./bin/discord-ghost" --targets node-linux-x64 "./dist/index.js"
        - cp ./node_modules/better-sqlite3/build/better_sqlite3.node ./bin/
        - cp ./node_modules/better-sqlite3/build/integer.node ./bin/
        - zip ./bin "$TRAVIS_OS_NAME.zip"
    - stage: Build and deploy
      os: osx
      before_deploy:
        - npm run build
        - pkg -o "./bin/discord-ghost" --targets node-macos-x64 "./dist/index.js"
        - cp ./node_modules/better-sqlite3/build/better_sqlite3.node ./bin/
        - cp ./node_modules/better-sqlite3/build/integer.node ./bin/
        - zip ./bin "$TRAVIS_OS_NAME.zip"
      deploy:
        provider: releases
        api_key: "$GH_TOKEN"
        skip_cleanup: true
        file: "$TRAVIS_OS_NAME.zip"
    - stage: Build and deploy
      os: windows
      before_deploy:
        - npm run build
        - pkg -o "./bin/discord-ghost" --targets node-win-x64 "./dist/index.js"
        - cp ./node_modules/better-sqlite3/build/better_sqlite3.node ./bin/
        - cp ./node_modules/better-sqlite3/build/integer.node ./bin/
        - zip ./bin "$TRAVIS_OS_NAME.zip"
      deploy:
        provider: releases
        api_key: "$GH_TOKEN"
        skip_cleanup: true
        file: "$TRAVIS_OS_NAME.zip"