language: node_js
node_js:
  - "lts/*"
before_script:
  - npm install -g pkg
script:
  - 'if [ "$TRAVIS_OS_NAME" != "windows" ]; then npm run lint; fi'
  - npm test
  - npm run coverage
  - npm run build
after_success:
  - mkidr bin
  - cp ./node_modules/better-sqlite3/build/better_sqlite3.node ./bin/
jobs:
  include:
    # Define the release stage that runs semantic-release
    - stage: Release Windows
      os: windows
      deploy:
        provider: script
        skip_cleanup: true
        script: pkg -o ./bin/discord-ghost ./dist/index.js --targets node10-win-x64 && npx semantic-release
    - stage: Release OSX
      os: osx
      deploy:
        provider: script
        skip_cleanup: true
        script: pkg -o ./bin/discord-ghost ./dist/index.js --targets node10-macos-x64 && npx semantic-release
    - stage: Release Linux
      os: linux
      deploy:
        provider: script
        skip_cleanup: true
        script: pkg -o ./bin/discord-ghost ./dist/index.js --targets node10-linux-x64 && npx semantic-release
